from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font-size: 16px;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.framefundo = QtWidgets.QFrame(self.centralwidget)
        self.framefundo.setStyleSheet("background-color: rgb(255, 204, 229);")
        self.framefundo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framefundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framefundo.setObjectName("framefundo")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.framefundo)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.framefundo)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.frameentrada = QtWidgets.QFrame(self.framefundo)
        self.frameentrada.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 204, 229);\n"
"")
        self.frameentrada.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameentrada.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameentrada.setObjectName("frameentrada")
        self.gridLayout = QtWidgets.QGridLayout(self.frameentrada)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelOrigen = QtWidgets.QLabel(self.frameentrada)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setFamily("Arial")
        self.labelOrigen.setFont(font)
        self.labelOrigen.setStyleSheet("background-color: rgb(255, 102, 178);")
        self.labelOrigen.setObjectName("labelOrigen")
        self.gridLayout_6.addWidget(self.labelOrigen, 0, 0, 1, 1)
        self.DestinolineEdit = QtWidgets.QLineEdit(self.frameentrada)
        self.DestinolineEdit.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.DestinolineEdit.setObjectName("DestinolineEdit")
        self.gridLayout_6.addWidget(self.DestinolineEdit, 1, 1, 1, 1)
        self.labelDestino = QtWidgets.QLabel(self.frameentrada)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setFamily("Arial")
        self.labelDestino.setFont(font)
        self.labelDestino.setStyleSheet("background-color: rgb(255, 102, 178);")
        self.labelDestino.setObjectName("labelDestino")
        self.gridLayout_6.addWidget(self.labelDestino, 1, 0, 1, 1)
        self.OrigenlineEdit = QtWidgets.QLineEdit(self.frameentrada)
        self.OrigenlineEdit.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.OrigenlineEdit.setObjectName("OrigenlineEdit")
        self.gridLayout_6.addWidget(self.OrigenlineEdit, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.BotonBusqueda = QtWidgets.QPushButton(self.frameentrada)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setFamily("Arial")
        self.BotonBusqueda.setFont(font)
        self.BotonBusqueda.setStyleSheet("background-color: rgb(204, 0, 102);\n"
"")
        self.BotonBusqueda.setObjectName("BotonBusqueda")
        self.gridLayout.addWidget(self.BotonBusqueda, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frameentrada, 1, 0, 1, 1)
        self.RespInterfaz = QtWidgets.QLabel(self.framefundo)
        self.RespInterfaz.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.RespInterfaz.setText("")
        self.RespInterfaz.setObjectName("RespInterfaz")
        self.gridLayout_4.addWidget(self.RespInterfaz, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.framefundo, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MENOR RUTA: METRO CDMX"))
        self.label.setText(_translate("MainWindow", "Escriba la estación de origen y la destino para calcular la ruta"))
        self.labelOrigen.setText(_translate("MainWindow", "Estación de Origen"))
        self.labelDestino.setText(_translate("MainWindow", "Estación Destino"))
        self.BotonBusqueda.setText(_translate("MainWindow", "Calcular la ruta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui =Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())